language: node_js
install:
  - yarn --ignore-engines --production=true
node_js:
  - 8
  - 10
before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
script:
  - npm run lint
  - npm run test
  - fossa
cache: yarn
